
CONST_IP_TOS_NET_CTRL = 0b111
CONST_IP_TOS_INTNET_CTRL = 0b110
CONST_IP_TOS_CRITIC_ECP = 0b101
CONST_IP_TOS_FLASH_OVERRIDE = 0b100
CONST_IP_TOS_FLASH = 0b011
CONST_IP_TOS_IMMEDIATE = 0b010
CONST_IP_TOS_PRIORITY = 0b001
CONST_IP_TOS_ROUTINE = 0b000

CONST_IP_TOS_MIN_DELAY = 0b00010000
CONST_IP_TOS_MAX_THROUGHPUT = 0b00001000
CONST_IP_TOS_MAX_RELIABILITY = 0b00000100
CONST_IP_TOS_MIN_COST = 0b00000010
CONST_IP_TOS_NORMAL = 0b00000000
CONST_IP_TOS_EF = 0xb8


const_list = {
    "IP_TOS_NET_CTRL": CONST_IP_TOS_NET_CTRL,
    "IP_TOS_INTNET_CTRL": CONST_IP_TOS_INTNET_CTRL,
    "IP_TOS_CRITIC_ECP": CONST_IP_TOS_CRITIC_ECP,
    "IP_TOS_FLASH_OVERRIDE": CONST_IP_TOS_FLASH_OVERRIDE,
    "IP_TOS_FLASH": CONST_IP_TOS_FLASH,
    "IP_TOS_IMMEDIATE": CONST_IP_TOS_IMMEDIATE,
    "IP_TOS_PRIORITY": CONST_IP_TOS_PRIORITY,
    "IP_TOS_ROUTINE": CONST_IP_TOS_ROUTINE,
    "IP_TOS_MIN_DELAY": CONST_IP_TOS_MIN_DELAY,
    "IP_TOS_MAX_THROUGHPUT": CONST_IP_TOS_MAX_THROUGHPUT,
    "IP_TOS_MAX_RELIABILITY": CONST_IP_TOS_MAX_RELIABILITY,
    "IP_TOS_MIN_COST": CONST_IP_TOS_MIN_COST,
    "IP_TOS_MIN_NORMAL": CONST_IP_TOS_NORMAL,
    "IP_TOS_EF": CONST_IP_TOS_EF,
}


def const_value(const: str) -> int:
    return const_list.get(const, 0)
