from enum import Enum, auto


class Tok(Enum):
    SELECT = auto()
    FROM = auto()
    INCLUDE = auto()
    WHERE = auto()
    ORDER_BY = auto()
    GROUP_BY = auto()
    ASC = auto()
    DESC = auto()
    BETWEEN = auto()
    TOP = auto()
    LIMIT = auto()
    IN = auto()
    LAND = auto()
    LOR = auto()
    NOW = auto()
    VAR = auto()
    CONST = auto()
    EOL = auto()
    EOF = auto()
    FILTER = auto()
    OUTPUT = auto()
    TO = auto()

    #--- Types
    INTEGER = auto()
    FLOAT = auto()
    IPV4 = auto()
    MAC = auto()
    DATE = auto()
    STRING = auto()
    CHAR = auto()
    NAME = auto()
    LABEL = auto()
    TRUE = auto()
    FALSE = auto()

    # --- One character keywords
    ASSIGN = auto()
    MASK = auto()
    WILDCARD = auto()
    TIMES = auto()
    SEMI = auto()
    DELIMITER = auto()
    GT = auto()
    LT = auto()
    LBRACE = auto()
    RBRACE = auto()
    PLUS = auto()
    MINUS = auto()
    LPAREN = auto()
    RPAREN = auto()
    LNOT = auto()

    # --- Two character keywords
    EQ = auto()
    LE = auto()
    GE = auto()
    NE = auto()
